name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the main branch
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0
    - name: Configure Git for the push from the workflow to the repository
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Print directory size before filter-branch
      run: du -sh .
    - name: Run the workflow script
      run: |
        FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --force --index-filter "git rm --cached --ignore-unmatch -r docs" --prune-empty --tag-name-filter cat -- --all
        mkdir docs
        date > docs/index.html
    - name: Print directory size after filter-branch
      run: du -sh .
    - name: Stage the Git index changes resulting from the CI script
      run: git add docs
    - name: Reset unstaged changes so that Git commit won't fail (e.g. package-lock.json, temporary files, …)
      run: git checkout -- .
    - name: Commit the staged changes to the workflow repository
      run: git commit -m "Replace generated docs content"
    - name: Push the commit to the workflow repository
      run: git push --force
